"use client";

import { useEffect, useMemo, useState } from "react";
import { OperationalWorkspace } from "./operational-workspace";

type System = { id:string; name:string; owner:string; region:string; purpose:string; risk:"Critical"|"High"|"Medium"|"Low"; status:"Action required"|"In review"|"Approved"; model:string; data:string; updated:string };

const systems:System[] = [
  { id:"AI-024", name:"Retail credit decisioning", owner:"Consumer Lending", region:"Nigeria · Ghana", purpose:"Credit eligibility and limit recommendations", risk:"Critical", status:"Action required", model:"In-house gradient model", data:"Identity · Transactions · Credit", updated:"2h ago" },
  { id:"AI-018", name:"Customer support copilot", owner:"Customer Experience", region:"Kenya · Uganda", purpose:"Agent response drafting and case summaries", risk:"High", status:"In review", model:"Azure OpenAI GPT-4.1", data:"Customer profile · Support history", updated:"Yesterday" },
  { id:"AI-011", name:"Network anomaly detection", owner:"Network Operations", region:"South Africa", purpose:"Identify network faults and traffic anomalies", risk:"Medium", status:"Approved", model:"Vertex AI AutoML", data:"Device · Location · Network telemetry", updated:"4 days ago" },
  { id:"AI-006", name:"Marketing propensity", owner:"Growth", region:"Nigeria · Kenya · Ghana", purpose:"Next-best-offer recommendations", risk:"Medium", status:"Approved", model:"Amazon SageMaker", data:"Transactions · App behavior", updated:"9 days ago" },
];
const riskTone:Record<System["risk"],string> = { Critical:"risk critical", High:"risk high", Medium:"risk medium", Low:"risk low" };
const nav=["Overview","Agency & adoption","Africa-first design","Sovereign resilience","Implementation capacity","Workforce absorption","Infrastructure dividend","Agrifood supply chains","Public-sector AI","Strategic foresight","AI systems","Deployment gate","AI agents","Continuous authorization","Model versions","Model retirement","Risk reviews","Vendor risk","AI competency","Compliance monitoring","Board reporting","Control library","Legal source register","Regulatory horizon","Guardrail decisions","Approvals & overrides","Evidence","Evidence export","Incidents & CAPA","Confidential reporting","Privacy","African privacy compliance","Policies","Audit trail","Users & roles","Safety guardrails","Terms"] as const;
type Section = typeof nav[number];

export default function Home() {
  const [active,setActive]=useState<Section>("Overview"); const [query,setQuery]=useState(""); const [records,setRecords]=useState<System[]>(systems); const [selected,setSelected]=useState<System>(systems[0]); const [showRegister,setShowRegister]=useState(false); const [mobileMenu,setMobileMenu]=useState(false); const [notice,setNotice]=useState("");
  const filtered=useMemo(()=>records.filter(s=>`${s.name} ${s.owner} ${s.region}`.toLowerCase().includes(query.toLowerCase())),[query,records]);
  function flash(message:string){setNotice(message);window.setTimeout(()=>setNotice(""),2600)}
  function navigate(section:Section){
    setActive(section);setMobileMenu(false);setShowRegister(false);
    const url=new URL(window.location.href);
    if(section==="Overview")url.searchParams.delete("section");else url.searchParams.set("section",section);
    window.history.pushState({section},"",`${url.pathname}${url.search}${url.hash}`);
    window.scrollTo({top:0,behavior:"auto"});
  }
  useEffect(()=>{
    const syncFromHistory=()=>{const section=new URL(window.location.href).searchParams.get("section");setActive(nav.includes(section as Section)?section as Section:"Overview");setMobileMenu(false);setShowRegister(false)};
    syncFromHistory();window.addEventListener("popstate",syncFromHistory);return()=>window.removeEventListener("popstate",syncFromHistory)
  },[]);
  useEffect(()=>{ fetch("/api/systems").then(r=>r.ok?r.json():null).then(data=>{if(data?.systems?.length){const saved:System[]=data.systems.map((s:Record<string,string>)=>({id:s.systemCode,name:s.name,owner:s.owner,region:s.region,purpose:s.purpose,risk:s.risk as System["risk"],status:s.status as System["status"],model:s.model,data:s.data,updated:"Saved record"}));setRecords([...saved,...systems])}}).catch(()=>undefined) },[]);
  async function register(form:HTMLFormElement){const formData=new FormData(form);const payload=Object.fromEntries(formData.entries());const response=await fetch("/api/systems",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!response.ok)throw new Error("Registration failed");const {system:s}=await response.json();const record:System={id:s.systemCode,name:s.name,owner:s.owner,region:s.region,purpose:s.purpose,risk:s.risk,status:s.status,model:s.model,data:s.data,updated:"Just now"};setRecords(current=>[record,...current]);setSelected(record)}
  return <main className="app-shell">
    <aside className="sidebar">
      <div className="brand"><img src="/sentinel-logo.svg" alt="Sentinel" /></div>
      <div className="workspace-label">Institution</div><button className="workspace-switch">Pan-African Trust Bank <span>⌄</span></button>
      <nav aria-label="Primary navigation">{nav.map(item=><button key={item} className={active===item?"nav-item active":"nav-item"} aria-current={active===item?"page":undefined} onClick={()=>navigate(item)}><span className="nav-icon">{item==="Overview"?"⌂":item==="AI systems"?"◇":item==="Reviews"?"◎":item==="Approvals"?"✓":item==="Evidence"?"▱":item==="Safety guardrails"?"⊘":item==="Privacy"?"◈":item==="Terms"?"¶":"↗"}</span>{item}{item==="Actions"&&<span className="nav-count">3</span>}</button>)}</nav>
      <div className="side-card"><div className="side-card-title">Governance coverage</div><div className="coverage-number">4 <span>markets</span></div><div className="progress"><i/></div><p>12 of 16 jurisdiction controls mapped</p><button onClick={()=>flash("Coverage report opened")}>View coverage →</button></div>
      <div className="profile"><span className="avatar">RC</span><span><b>Reginald Coleman</b><small>Governance administrator</small></span><button>•••</button></div>
    </aside>
    <section className="content">
      <header className="topbar"><button className="mobile-menu-button" onClick={()=>setMobileMenu(v=>!v)} aria-expanded={mobileMenu} aria-label="Open navigation"><span>{mobileMenu?"×":"☰"}</span> Menu</button><div className="breadcrumb">CONTROL ROOM <span>/</span> {active.toUpperCase()}</div><div className="mobile-page-title">{active}</div><div className="top-actions"><label className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search systems, owners, markets"/></label><button className="icon-button">♢<i/></button><button className="primary register-button" onClick={()=>setShowRegister(true)}>＋ Register AI system</button></div></header>
      {mobileMenu&&<div className="mobile-nav"><div className="mobile-nav-head"><span>Navigate Sentinel</span><button onClick={()=>setMobileMenu(false)}>×</button></div>{nav.map(item=><button key={item} className={active===item?"active":""} aria-current={active===item?"page":undefined} onClick={()=>navigate(item)}><span>{item==="Overview"?"⌂":item==="AI systems"?"◇":item==="Reviews"?"◎":item==="Approvals"?"✓":item==="Evidence"?"▱":item==="Safety guardrails"?"⊘":item==="Privacy"?"◈":item==="Terms"?"¶":"↗"}</span>{item}{item==="Actions"&&<b>3</b>}</button>)}<button className="mobile-register" onClick={()=>{setMobileMenu(false);setShowRegister(true)}}>＋ Register AI system</button></div>}
      {active==="Safety guardrails"?<SafetyGuardrails flash={flash}/>:active==="Terms"?<TermsOfService/>:active!=="Overview"?<OperationalWorkspace key={active} section={active} flash={flash}/>:<div className="page">
        <div className="hero-row"><div><p className="eyebrow">INSTITUTIONAL AI GOVERNANCE</p><h1>Govern what your institution<br/>builds and buys.</h1><p className="lede">One defensible record of every AI system, decision, control and piece of evidence—across every market.</p></div><div className="assurance-score"><div className="score-ring"><span>74</span><small>/100</small></div><div><small>ASSURANCE SCORE</small><b>Needs attention</b><p>↑ 6 points this quarter</p></div></div></div>
        <section className="metrics"><article><span className="metric-icon blue">◇</span><div><small>REGISTERED SYSTEMS</small><b>24</b><p>4 added this month</p></div></article><article><span className="metric-icon red">!</span><div><small>HIGH-RISK SYSTEMS</small><b>7</b><p>3 require action</p></div></article><article><span className="metric-icon amber">◴</span><div><small>OPEN REVIEWS</small><b>5</b><p>2 due this week</p></div></article><article><span className="metric-icon green">✓</span><div><small>EVIDENCE COVERAGE</small><b>82%</b><p>↑ 9% since May</p></div></article></section>
        <div className="dashboard-grid">
          <section className="panel systems-panel"><div className="panel-head"><div><p className="eyebrow">SYSTEM REGISTER</p><h2>AI systems requiring attention</h2></div><button onClick={()=>navigate("AI systems")}>View all 24 →</button></div><div className="table-wrap"><table><thead><tr><th>System</th><th>Markets</th><th>Risk</th><th>Status</th><th/></tr></thead><tbody>{filtered.map(s=><tr key={s.id} onClick={()=>setSelected(s)} className={selected.id===s.id?"selected":""}><td><b>{s.name}</b><small>{s.id} · {s.owner}</small></td><td>{s.region}</td><td><span className={riskTone[s.risk]}>{s.risk}</span></td><td><span className={`status ${s.status.replace(" ","-").toLowerCase()}`}>{s.status}</span></td><td>›</td></tr>)}</tbody></table></div></section>
          <aside className="panel detail-panel"><div className="detail-top"><span className={riskTone[selected.risk]}>{selected.risk} risk</span><button>•••</button></div><p className="eyebrow">{selected.id}</p><h2>{selected.name}</h2><p className="detail-purpose">{selected.purpose}</p><dl><div><dt>Accountable owner</dt><dd>{selected.owner}</dd></div><div><dt>Deployed markets</dt><dd>{selected.region}</dd></div><div><dt>Model / provider</dt><dd>{selected.model}</dd></div><div><dt>Data categories</dt><dd>{selected.data}</dd></div></dl><div className="control-block"><div><span>Control evidence</span><b>8 of 12 complete</b></div><div className="progress wide"><i style={{width:"67%"}}/></div></div><div className="finding"><span>!</span><div><b>Human appeal route missing</b><p>Required for automated credit decisions in Nigeria.</p></div></div><div className="detail-actions"><button onClick={()=>flash("Risk review opened")}>Open risk review</button><button className="plain" onClick={()=>navigate("Evidence")}>View evidence</button></div></aside>
        </div>
        <section className="lower-grid"><article className="panel action-panel"><div className="panel-head"><div><p className="eyebrow">CORRECTIVE ACTIONS</p><h2>What needs to move next</h2></div><button onClick={()=>navigate("Incidents & CAPA")}>Open action log →</button></div>{[["P1","Document credit appeal pathway","Retail credit decisioning · Nigeria","Due Aug 19","AO"],["P2","Complete vendor model assessment","Customer support copilot · Kenya","Due Aug 23","JM"],["P2","Renew data transfer assessment","Marketing propensity · Ghana","Due Aug 28","NK"]].map((a,i)=><div className="action-row" key={a[1]}><span className={`priority p${i?2:1}`}>{a[0]}</span><div><b>{a[1]}</b><p>{a[2]}</p></div><time>{a[3]}</time><span className="owner">{a[4]}</span></div>)}</article><article className="panel jurisdiction-panel"><div className="panel-head"><div><p className="eyebrow">JURISDICTIONS</p><h2>Control readiness</h2></div></div>{[["Nigeria",76,"2 gaps"],["Kenya",88,"1 gap"],["Ghana",81,"2 gaps"],["Uganda",69,"4 gaps"]].map(([name,value,gaps])=><div className="jurisdiction" key={name}><span>{name}</span><div className="progress wide"><i style={{width:`${value}%`}}/></div><b>{value}%</b><small>{gaps}</small></div>)}</article></section>
      </div>}
    </section>
    {showRegister&&<div className="modal-backdrop" onMouseDown={()=>setShowRegister(false)}><form className="modal" onMouseDown={e=>e.stopPropagation()} onSubmit={async e=>{e.preventDefault();try{await register(e.currentTarget);setShowRegister(false);flash("AI system registered for initial review")}catch{flash("Record could not be saved. Please try again.")}}}><div className="modal-head"><div><p className="eyebrow">NEW GOVERNANCE RECORD</p><h2>Register an AI system</h2></div><button type="button" onClick={()=>setShowRegister(false)}>×</button></div><label>System name<input name="name" required placeholder="e.g. Fraud detection engine"/></label><div className="field-grid"><label>Accountable owner<input name="owner" required placeholder="Business function"/></label><label>Deployed market<select name="region"><option>Nigeria</option><option>Kenya</option><option>Ghana</option><option>Uganda</option><option>South Africa</option></select></label></div><label>Business purpose<textarea name="purpose" required placeholder="What decision or workflow does this system support?"/></label><div className="field-grid"><label>Model provider<input name="model" placeholder="Internal or external provider"/></label><label>Initial risk<select name="risk"><option value="Medium">Not yet assessed</option><option value="High">Potentially high risk</option><option value="Low">Low risk</option></select></label></div><div className="modal-actions"><button type="button" onClick={()=>setShowRegister(false)}>Cancel</button><button className="primary" type="submit">Register and begin review</button></div></form></div>}
    {notice&&<div className="toast"><span>✓</span>{notice}</div>}
  </main>
}

function SafetyGuardrails({flash}:{flash:(message:string)=>void}){
  const [controls,setControls]=useState([true,true,true,true,true,false]);
  const rules=[
    ["Human approval for consequential decisions","Credit, employment, healthcare, insurance and access decisions cannot execute without an accountable human approver.","High-impact decisions"],
    ["Sensitive-data boundary","Prompts, training sets and retrieval sources are blocked from using unapproved identity, health, biometric or financial data.","Data protection"],
    ["Restricted-use screening","Systems are screened for prohibited surveillance, manipulation, social scoring and discriminatory profiling before deployment.","Acceptable use"],
    ["Explainability and appeal route","Affected people receive meaningful notice, a reason for the outcome and a channel to request human review.","Individual rights"],
    ["Model and vendor change control","Material model, provider, hosting or purpose changes automatically reopen the risk assessment.","Lifecycle control"],
    ["Automated incident containment","High-severity incidents can suspend the affected workflow and notify accountable owners automatically.","Incident response"],
  ];
  return <div className="page trust-page"><div className="trust-hero"><div><p className="eyebrow">ENFORCEMENT LAYER</p><h1>Safety guardrails</h1><p>Convert responsible-AI principles into controls that block, route, record and escalate institutional AI activity.</p></div><div className="trust-score"><span>5/6</span><small>controls enforced</small></div></div><div className="trust-layout"><section className="panel"><div className="panel-head"><div><p className="eyebrow">ACTIVE CONTROL SET</p><h2>Institution-wide guardrails</h2></div><span className="policy-version">POLICY v1.4</span></div><div className="guardrail-list">{rules.map((rule,i)=><article key={rule[0]}><div className={`guardrail-symbol ${controls[i]?"on":""}`}>{controls[i]?"✓":"!"}</div><div><div className="rule-meta">{rule[2]}</div><h3>{rule[0]}</h3><p>{rule[1]}</p></div><button className={controls[i]?"toggle on":"toggle"} aria-label={`Toggle ${rule[0]}`} onClick={()=>{setControls(c=>c.map((v,n)=>n===i?!v:v));flash(`${rule[0]} ${controls[i]?"paused":"enforced"}`)}}><i/></button></article>)}</div></section><aside className="trust-side"><section className="panel mini-panel"><p className="eyebrow">DECISION GATE</p><h2>Before any system goes live</h2>{["Named accountable owner","Completed impact assessment","Documented lawful data basis","Independent validation evidence","Human override tested"].map((x,i)=><div className="check-line" key={x}><span>{i<4?"✓":"○"}</span>{x}</div>)}<button className="full-action" onClick={()=>flash("Deployment gate review opened")}>Review deployment gate</button></section><section className="panel incident-card"><span className="incident-icon">!</span><div><p className="eyebrow">OPEN SAFETY INCIDENT</p><h3>Credit model drift threshold exceeded</h3><p>AI-024 · Nigeria · detected 48 minutes ago</p></div><button onClick={()=>flash("Incident response opened")}>Open incident →</button></section></aside></div></div>
}

// Retained as the designed privacy overview while the live privacy workflow uses OperationalWorkspace.
// eslint-disable-next-line @typescript-eslint/no-unused-vars
function PrivacyCenter({flash}:{flash:(message:string)=>void}){
  return <div className="page trust-page"><div className="trust-hero"><div><p className="eyebrow">DATA GOVERNANCE</p><h1>Privacy center</h1><p>See what personal data AI systems use, why it is processed, where it moves and how individual rights are fulfilled.</p></div><button className="primary" onClick={()=>flash("Privacy assessment started")}>＋ New privacy assessment</button></div><section className="privacy-metrics"><article><small>PROCESSING ACTIVITIES</small><b>31</b><p>Across 24 AI systems</p></article><article><small>CROSS-BORDER TRANSFERS</small><b>8</b><p>2 require renewal</p></article><article><small>RIGHTS REQUESTS</small><b>3</b><p>All within response target</p></article><article><small>RETENTION EXCEPTIONS</small><b>2</b><p>Owner action required</p></article></section><div className="trust-layout privacy-layout"><section className="panel"><div className="panel-head"><div><p className="eyebrow">DATA FLOW REGISTER</p><h2>Personal-data use by AI systems</h2></div><button>Export record →</button></div><div className="privacy-table"><div className="privacy-row head"><span>System</span><span>Purpose & basis</span><span>Hosting</span><span>Retention</span><span>Status</span></div>{[["Retail credit decisioning","Eligibility · Contract / legal obligation","Lagos · Azure South Africa","7 years","Review"],["Customer support copilot","Service support · Legitimate interest","EU West · Kenya cache","24 months","Approved"],["Marketing propensity","Personalization · Consent","AWS Cape Town","12 months","Action"],["Network anomaly detection","Service security · Legitimate interest","Johannesburg","90 days","Approved"]].map(row=><div className="privacy-row" key={row[0]}>{row.map((cell,i)=><span key={cell} className={i===4?`privacy-state ${cell.toLowerCase()}`:""}>{cell}</span>)}</div>)}</div></section><aside className="trust-side"><section className="panel mini-panel"><p className="eyebrow">PRIVACY CONTROLS</p><h2>Protection status</h2>{[["Purpose limitation",92],["Data minimization",78],["Retention enforcement",71],["Transfer safeguards",83],["Rights fulfillment",96]].map(([x,n])=><div className="privacy-control" key={x}><div><span>{x}</span><b>{n}%</b></div><div className="progress wide"><i style={{width:`${n}%`}}/></div></div>)}</section><section className="panel mini-panel"><p className="eyebrow">INDIVIDUAL RIGHTS</p><h2>Request workflow</h2><p className="mini-copy">Access, correction, deletion, objection, portability and human-review requests are logged with identity verification, deadlines and evidence.</p><button className="full-action" onClick={()=>flash("Rights request workflow opened")}>Open request queue</button></section></aside></div></div>
}

function TermsOfService(){
 const sections=[["1. Platform and scope","Sentinel provides institutional tools for recording, reviewing, approving and monitoring artificial-intelligence systems. The platform supports governance processes; it does not replace legal advice, regulatory determinations, independent validation or accountable human judgment."],["2. Authorized institutional use","Customers must ensure that users are authorized, information entered is accurate, and use complies with applicable law, internal policy and contractual obligations. The platform may not be used to enable unlawful surveillance, discrimination, manipulation or decisions that remove required human oversight."],["3. Customer data and responsibility","The customer retains responsibility for its institutional records, uploaded evidence and system decisions. The customer must have a lawful basis for personal data it enters and must avoid submitting unnecessary sensitive data, credentials or production secrets."],["4. AI-generated assistance","Automated classifications, summaries, control suggestions and jurisdiction mappings are decision-support outputs. They may be incomplete or become outdated. Qualified personnel must review outputs before relying on them for deployment, compliance or individual decisions."],["5. Security and access","Users must protect their credentials, maintain appropriate access rights and report suspected compromise promptly. We may restrict access when necessary to protect users, data, the service or affected individuals."],["6. Service records and availability","The platform maintains operational records to support auditability and security. Availability, support, retention and recovery commitments are governed by the applicable customer order or service agreement."],["7. Suspension and termination","Access may be suspended for material breach, unlawful use, security risk or nonpayment. On termination, customer data will be handled according to the applicable agreement, retention schedule and legal requirements."],["8. Disclaimers and liability","The service is provided subject to the warranties and liability limits in the applicable customer agreement. No platform output guarantees regulatory approval, legal compliance or the absence of AI-related harm."],["9. Changes and governing terms","Material changes will be communicated through the platform or customer contact. A signed customer agreement controls if it conflicts with these online terms."]];
 return <div className="page terms-page"><div className="terms-header"><div><p className="eyebrow">LEGAL · OPERATIONAL DRAFT</p><h1>Platform Terms of Service</h1><p>Effective August 16, 2026 · Version 0.9</p></div><span>Counsel review required before public launch</span></div><div className="terms-layout"><aside><b>Contents</b>{sections.map(s=><a href={`#term-${s[0][0]}`} key={s[0]}>{s[0]}</a>)}</aside><article className="terms-document"><div className="legal-notice"><b>Important:</b> These terms are a founder-ready operational draft. Local counsel should finalize governing law, liability, data-processing, regulatory and customer-contract provisions before public use.</div>{sections.map(s=><section id={`term-${s[0][0]}`} key={s[0]}><h2>{s[0]}</h2><p>{s[1]}</p></section>)}<section><h2>Contact</h2><p>Questions about these terms, privacy or platform safety may be directed to the organization’s designated legal or privacy contact.</p></section></article></div></div>
}
